Upgrade to ROS Noetic & Ubuntu 20.04
Helbling-Technik/HelMoRo-software pull request #21
Opened 2024-05-22 13:36 UTC by bamertsa

This pull request...

... updates the cmake minimum required version to 3.10.2
... required OpenCV version is now 4.2
... corrects some previous mistakes
... fixes an issue were redundant nodes were started

2024-05-23 11:26 UTC, jonaslondschien-helbling requested changes
I added a few questions/comments, please have a look

2024-05-23 11:26 UTC, jonaslondschien-helbling commented on helmoro_2dnav/CMakeLists.txt
>  ## Compile as C++11, supported in ROS Kinetic and newer
Change comment, I suggest to search through the repo for the `kinetic` keyword

2024-05-23 11:26 UTC, jonaslondschien-helbling commented on helmoro_2dnav/move_base.launch
> +  <node name="map_server" pkg="map_server" type="map_server" args="$(find helmoro_2dnav)/helmoro_maps/sif_table_gazebo.yaml" />
In Simulation it now finds the package as well?
Or should the default be the gazebo room?

2024-05-23 11:26 UTC, jonaslondschien-helbling commented on helmoro_description/launch/rviz_helmoro.launch
> +  <!-- <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
Don't hesitate to delete this, it is the git history in the worst case

2024-05-23 11:26 UTC, jonaslondschien-helbling commented on helmoro_description/launch/helmoro.launch
> +    <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen" args="-urdf -model helmoro -param helmoro_description/urdf -x 0 -y 0 -z 0.1"/>
why did you change the spawn location?

2024-05-23 11:26 UTC, jonaslondschien-helbling commented on helmoro_state_publisher/src/HelmoroStatePublisher.cpp
> +    auto workerTimeStep = param<double>("time_step_pub", 0.02);
If there is not specific reason for the change I would revert this.

2024-05-23 11:29 UTC, bamertsa commented on helmoro_description/launch/rviz_helmoro.launch
> +  <!-- <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
Will do

2024-05-23 11:30 UTC, bamertsa commented on helmoro_description/launch/helmoro.launch
> +    <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen" args="-urdf -model helmoro -param helmoro_description/urdf -x 0 -y 0 -z 0.1"/>
The Robot spawned very close to the wall, leading to some issues

2024-05-23 11:31 UTC, bamertsa commented on helmoro_2dnav/CMakeLists.txt
>  ## Compile as C++11, supported in ROS Kinetic and newer
Will do

2024-05-23 11:33 UTC, bamertsa commented on helmoro_2dnav/move_base.launch
> +  <node name="map_server" pkg="map_server" type="map_server" args="$(find helmoro_2dnav)/helmoro_maps/sif_table_gazebo.yaml" />
Yes. it does. It already was the same package, I only simplified the code. I tested both in simulation and on the robot.

2024-05-23 12:43 UTC, bamertsa commented on helmoro_state_publisher/src/HelmoroStatePublisher.cpp
> +    auto workerTimeStep = param<double>("time_step_pub", 0.02);
This change is needed for the "TF_REPEATED_DATA" warnings to mostly disapear

2024-05-24 07:04 UTC, jonaslondschien-helbling requested changes

2024-05-24 07:04 UTC, jonaslondschien-helbling commented on helmoro_2dnav/CMakeLists.txt
> -)
Is this deleted on purpouse? I would leave this in the CMake, because it defines the catkin_make structure of this file

2024-05-24 07:04 UTC, jonaslondschien-helbling commented on helmoro_2dnav/CMakeLists.txt
> -## Compile as C++11, supported in ROS Kinetic and newer
I did not realize this is a comment for a possible compile flag. Maybe add it again?
My mistake

2024-05-24 07:04 UTC, jonaslondschien-helbling commented on helmoro_2dnav/CMakeLists.txt
> -## Compile as C++11, supported in ROS Kinetic and newer
Same for the other files

2024-05-24 07:04 UTC, jonaslondschien-helbling commented on object_detector/CMakeLists.txt
> -#message(${OpenCV_LIBS})
This delete makes sense.
Did you test this package?

2024-05-24 07:28 UTC, bamertsa commented on object_detector/CMakeLists.txt
> -#message(${OpenCV_LIBS})
I tested the package in simulation

2024-05-24 07:37 UTC, jonaslondschien-helbling approved these changes

2024-05-24 07:38 UTC, merged